name: Android CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build TurboLite Optimizer APK
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # ✅ Grant execution permission for Gradle
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # ✅ Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # ✅ Build debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # ✅ Upload build artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: TurboLiteOptimizer-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      # ✅ Optional: Print APK size
      - name: Show APK size
        run: ls -lh app/build/outputs/apk/debug/
